{% set name = "helios" %}
{% set version = "2.0.0a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: helios-{{ version }}.tar.gz
  url:  https://github.com/3dgeo-heidelberg/helios/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 95451bdf14e6a5e75fa01573c8ab03221b767595a29e78a33d7f435eb627aa73

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  script_env:
    # GitHub provided tarballs do not contain the metadata required by setuptools_scm.
    # We therefore manually inject the (known) version number into the build environment.
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - cmake
    - make
  host:
    - armadillo
    - glm
    - lastools
    - libblas
    - liblapack
    - libboost-python-devel
    - libboost-devel
    - libgdal
    - pip
    - python
    - scikit-build-core
    - setuptools_scm
    - tinyxml2
    - zlib
  run:
    - importlib_resources  
    - lastools
    - libgdal
    - matplotlib-base
    - python
    - xmlschema

test:
  imports:
    - pyhelios
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/3dgeo-heidelberg/helios
  summary: 'Heidelberg LiDAR Operations Simulator ++'
  description: |
    HELIOS++ is a general-purpose software package for simulation of terrestrial,
    mobile and airborne laser scanning surveys written in C++11. It is developed
    and maintained by the 3DGeo Research Group at Heidelberg University.
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dokempf
    - lwiniwar
    - bhoefle-3dgeo
    - han16nah
