{% set name = "helios" %}
{% set version = "2.0.0a3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: helios-{{ version }}.tar.gz
  url:  https://github.com/3dgeo-heidelberg/helios/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cfda8ed8574153d0594d71347d3613821dd03c4c11fb01f69516bc205ae52858

build:
  entry_points:
    - helios = pyhelios.__main__:helios_entrypoint
    - helios-live = pyhelios.live:helios_live
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  script_env:
    # GitHub provided tarballs do not contain the metadata required by setuptools_scm.
    # We therefore manually inject the (known) version number into the build environment.
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - armadillo
    - glm
    - lastools
    - libblas
    - liblapack
    - libboost-python-devel
    - libboost-devel
    - libgdal
    - pip
    - python
    - scikit-build-core
    - setuptools_scm
    - tinyxml2
    - zlib
  run:
    - importlib_resources  
    - lastools
    - libgdal
    - matplotlib-base
    - python
    - xmlschema

test:
  imports:
    - pyhelios
  requires:
    - pip
  commands:
    - pip check
    - helios --help
    - helios-live --help

about:
  home: https://github.com/3dgeo-heidelberg/helios
  summary: 'Heidelberg LiDAR Operations Simulator ++'
  description: |
    HELIOS++ is a general-purpose software package for simulation of terrestrial,
    mobile and airborne laser scanning surveys written in C++11. It is developed
    and maintained by the 3DGeo Research Group at Heidelberg University.
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dokempf
    - lwiniwar
    - bhoefle-3dgeo
    - han16nah
